import React from "react";
import "./globals.css";
import { Inter } from "next/font/google";
import Nav from "@/components/Nav";
import CookieCard from "@/components/CookieCard";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ashkan Sotoudeh",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body className={inter.className}>
        {/* <CookieCard /> */}
        <Nav />
        {children}
      </body>
    </html>
  );
}
